### ISSUE TITLE
Bots Don't Work

### ISSUE THREAD

**Issue by MarkBemjanim** [tf2classic/tf2classic-issue-tracker#231]
Most of the time when I join a game that automatically spawns player bots, they don't do anything. They just stay in their spawn rooms unmoving.
Also, it said to check if my issue has already been reported, but I have no idea how to check that cuz I have no idea what Github even is. I just made this account so I can report this issue.

**Comment by MaartenS11** [comment]
Bots only move if they have a navigation mesh, some maps have a nav mesh packaged with the game others do not. Most likely you are playing maps that do not have a nav mesh. On these maps bots will just stand still. 

You can try generating a nav mesh by making use of the `nav_generate` command.

**Comment by SilentFox3** [comment]
To add onto this, if I may, Navmesh files for maps are usually rendered as .nav files in your file system, so if a given map didn't come with one when you installed it, you'll _most likely_ need to generate a new one, as Maarten said. Some maps come with it pre-packaged, but those tend to be newer and rarer.

TF2C seems to make its own type of Navmesh files, though - they don't work in Live TF2, and importantly, Live TF2 navmeshes don't work out of the box in TF2C. If a map has a navmesh file, but bots on both teams still don't move anyway, it might be since it was for Live TF2. You'll get some errors related to it in your Dev. Console if so.

If you have the files, you can convert such a navmesh to TF2C's format using the command `tf2c_convert_nav_file filepath/input.nav filepath/output.nav` - where both input and output are file locations. Output just defaults to spitting it out in TF2C's main folder if you don't specify where to put the output nav.
