### ISSUE TITLE
Downloading problems

### ISSUE THREAD

**Issue by Demomanisspy** [tf2classic/tf2classic-issue-tracker#26]
When ever I click the download button, it just refreshes the page, how do I fix this?

**Comment by chloecormier** [comment]
You're not the first person to report this, but it's an extremely uncommon issue. What browser are you using? Can you go to https://tf2classic.com/download directly?

**Comment by NarwhalJamesx2** [comment]
I found solution
![Niksbigasshole](https://user-images.githubusercontent.com/107482519/173580399-dc562aa0-fd74-4dd6-9135-567dbdbef2a7.png)
![Niksbigasshole2](https://user-images.githubusercontent.com/107482519/173580405-dffd1acc-97c7-4bb3-9e67-d392fc2f5d71.png)

**Comment by Demomanisspy** [comment]
Yes I can get to there and I'm just using basic crome

**Comment by chloecormier** [comment]
We believe this is due to the website's design being misleading rather than any actual bug. The "Download" button on the top-right of the page does not actually download the game, it just brings you to the page that contains instructions for how to download the game (and if you're already on that page, it'll just refresh it). You will need to scroll down and follow the step-by-step installation instructions in order to get the game. We'll be changing the website to make this more clear soon.
