### ISSUE TITLE
can connect to server and weird display menu name

### ISSUE THREAD

**Issue by tutusvano** [tf2classic/tf2classic-issue-tracker#273]
when i download the game and do the instructions and played it and i cannot connect to servers and the wepones have no names and the text have weird names on it can you fix it maybe i didnt follow the instructions correctly or soemthing else am forgeting on it

**Comment by sapphonie** [comment]
you should include screenshots with your message so we can help, or join our discord and we can help there

https://tf2classic.com/discord

**Comment by MaartenS11** [comment]
I think the most likely thing that happend here is that you have installed it incorrectly. The "weird names" are probably starting with #TF_ this means that localisation is not working which is probably because the directory the mod is installed in has the wrong name. You should have a directory called exactly "tf2classic" in the "sourcemods" directory. Most likely it is now something other than "tf2classic".

**Comment by sapphonie** [comment]
Needs more info. Please reopen if you have screenshots or something else.
