### ISSUE TITLE
[Suggestion] Non-weapon cosmetics auto-equipped/dequipped tied to weapons

### ISSUE THREAD

**Issue by moosetwin0** [tf2classic/tf2classic-issue-tracker#354]
I was playing on TF2C yesterday and I mentioned that it was difficult telling players apart due to the lack of cosmetics, someone mentioned this as a potential solution, and I thought it was a great idea.

This would both help tell players apart, and make it easier to tell which weapons a person has equipped.

An example of this could be Scout wearing a hardhat whenever he has the nail-gun equipped.

I seem to have issues adding labels on Github, so I apologize if this issue doesn't the Enhancement label.

**Comment by Technochips** [comment]
These are called wearables, and it is already used for the sandvich, the huntsman, the various mediguns, the gunboats, the dynamite pack, the harvester and Chekhov's punch. We already add them onto weapons when deemed appropriate, usually only if the weapon introduces a quirk or some passive effects that would be useful for other players to see from a distance.

The nailgun does not really need one because:

- it doesn't bring any passive effects
- he holds it 80% of the time, and a scout holding the nailgun is usually differentiable from a scout holding the scattergun

**Comment by moosetwin0** [comment]
Alright, thank you!
